import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import "./globals.css";
import MuiRegistry from "@/theme/muiRegistry";
import { ThemeContextProvider } from "@/theme/ThemeContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SocialMedia - App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="emotion-insertion-point" content="" />
      </head>
      <body
        className={`${inter.variable} antialiased`}
      >
        <MuiRegistry>
         <ThemeContextProvider>
            {children}
         </ThemeContextProvider>
        </MuiRegistry>
      </body>
    </html>
  );
}
